### ISSUE TITLE
For your sprint project boards, create issues, not just cards

### ISSUE THREAD

**Issue by dantogno** [JaredBronstein/Paper-Dungeon#2]
You can convert cards to issues, or just create issues first and then add them to the project board.

Issues are necessary because you can assign team members and add more detailed info. Cards are more for quick notes. Anything you're actually going to take action on should be converted to an issue and assigned.

Perhaps this link can help: https://help.github.com/en/articles/about-issues

**Comment by dantogno** [comment]
@Chaoskil @scalford @JaredBronstein Please address this as a priority.

**Comment by Chaoskil** [comment]
I at least did it and reminded the rest
